2021-02-23 17:20:05,069 DEBUG    [database_managment.py:26] New log file created and 'Database' object referred to utils/database_file.db.
2021-02-23 17:20:05,069 DEBUG    [database_managment.py:28] Checking if utils/database_file.db exists
2021-02-23 17:20:05,069 DEBUG    [database_managment.py:30] utils/database_file.db exists
2021-02-23 17:20:05,070 DEBUG    [database_managment.py:49] Checking if utils/database_file.db exists
2021-02-23 17:20:05,070 DEBUG    [database_managment.py:51] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-23 17:20:05,076 DEBUG    [app.py:30] Initializing Flask app.
2021-02-23 17:20:05,080 DEBUG    [app.py:34] Permanent session lifetime set
2021-02-23 17:20:05,092 WARNING  [_internal.py:113]  * Debugger is active!
2021-02-23 17:20:05,093 INFO     [_internal.py:113]  * Debugger PIN: 554-604-267
2021-02-23 17:27:19,943 INFO     [_internal.py:113]  * Detected change in '/home/lucsapiega/python/projects/fiados_project_flask/app.py', reloading
2021-02-23 17:27:19,986 INFO     [_internal.py:113]  * Restarting with stat
