2021-02-21 11:53:29,323 DEBUG    [database_managment.py:25] New log file created and 'Database' object referred to utils/database_file.db.
2021-02-21 11:53:29,323 DEBUG    [database_managment.py:44] Checking if utils/database_file.db exists
2021-02-21 11:53:29,324 DEBUG    [database_managment.py:46] utils/database_file.db exists. If 'operaciones' and 'saldos' tables don't exist, they will be created.
2021-02-21 11:53:29,449 DEBUG    [database_managment.py:153] Geting the names in the 'operaciones' table.
2021-02-21 11:53:29,450 DEBUG    [database_managment.py:157] Clients found. Saving them into a set
2021-02-21 11:53:29,450 DEBUG    [database_managment.py:162] Returning these clients as a list
2021-02-21 11:53:29,458 WARNING  [_internal.py:113]  * Debugger is active!
2021-02-21 11:53:29,458 INFO     [_internal.py:113]  * Debugger PIN: 234-919-219
